Создал кастомный менеджер модели
При выполнении команды python3 manage.py createsuperuser возникала ошибка TypeError: UserManager.create_superuser() missing 1 required positional argument: 'username'. В кастомной модели пользователя аргумент 'username' не требуется. Вместо него используется 'email'. В связи с этим был создан кастомный менеджер модели